import type { GetServerSideProps, InferGetServerSidePropsType } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Blob from '../components/Blob'
import sql from '../lib/postgres'

const inter = Inter({ subsets: ['latin'] })

type HomeProps = {
  numUsers: number
}

export const getServerSideProps: GetServerSideProps<HomeProps> = async () => {
  try {
    const result = await sql`select count(*)::int from saas.users`
    const numUsers = result[0].count
    return { props: { numUsers } }
  } catch (err) {
    console.error(err)
  }

  return { props: { numUsers: 0 } }
}

export default function Home({ numUsers }: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            <span>
              Get started by editing&nbsp;
              <code className={styles.code}>next-ts-app/src/app/page.tsx</code>,<br /> and visiting the{' '}
              <strong>JavaScript</strong> app.
            </span>
          </p>
          <div>
            <Link
              href="https://mproske.com?utm_source=index&utm_medium=ts-app&utm_campaign=nextjs-docker-production-kit"
              target="_blank"
              rel="noopener noreferrer"
            >
              Starter kit by Max Proske
            </Link>
          </div>
        </div>

        <div className={styles.center}>
          <Image className={styles.logo} src="/next.svg" alt="Next.js Logo" width={180} height={37} priority />
          <Blob />
        </div>

        <div className={styles.grid}>
          <Link href="/js" className={styles.card}>
            <h2 className={inter.className}>
              JavaScript app <span>-&gt;</span>
            </h2>
            <p className={inter.className}>Visit the JavaScript app.</p>
          </Link>

          <Link href="/your-app-here" className={styles.card}>
            <h2 className={inter.className}>
              Your app <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Your SaaS app here ({numUsers} {numUsers === 1 ? 'user' : 'users'}).
            </p>
          </Link>
        </div>
      </main>
    </>
  )
}
